services:
#  pgdog:
#    image: ghcr.io/pgdogdev/pgdog:main
#    volumes:
#      - ./docker/pgdog.toml:/pgdog/pgdog.toml
#      - ./docker/users.toml:/pgdog/users.toml
#    ports:
#      - 6432:6432
#    networks:
#      - postgres
#    environment:
#      RUST_LOG: debug
  shard_0:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - postgres
  shard_1:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  shard_2:
    image: postgres:17
    ports:
      - 5434:5432

    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql

networks:
  postgres:
